import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="bg-blue-500 text-red-500">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorem praesentium cupiditate
          porro facere culpa harum id quis, eaque laboriosam autem accusantium. Itaque alias, sed
          consectetur exercitationem doloribus ab id eaque!
        </p>
        <ul>
          <li>Item 1</li>
          <li>Item 2</li>
          <li>Item 3</li>
          <li>Item 4</li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
